"""Validate exact staged resources and emit final integrator contract."""
from donnager10_geometry_common import *
import struct
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();m=read(AUDIT/'mount-metadata.json');v=read(AUDIT/'output-validation.json');checks=read(AUDIT/'independent-checks.json');assert v['status'].startswith('PASS') and checks['status'].startswith('PASS');game=BUILD/'game';textures=[];materials=[];meshes=[];inherited=[]
for p in sorted((game/'textures').glob('*.dds')):
 b=p.read_bytes();assert b[:4]==b'DDS ';h,w=struct.unpack_from('<II',b,12);fourcc=b[84:88];assert fourcc in [b'DX10',b'BC5S'];fmt=struct.unpack_from('<I',b,128)[0] if fourcc==b'DX10' else 84;assert fmt==(84 if p.stem.endswith('_nrm') else 98);assert w==h and w in [4,16,2048];textures.append({'path':str(p),'sha256':sha(p),'dimensions':[w,h],'dxgi_format':fmt})
for p in sorted((game/'mesh_materials').glob('*.mesh_material')):
 d=read(p)
 for key,value in d.items():
  if key.endswith('_texture'):assert (game/'textures'/(value+'.dds')).is_file(),(p,key,value)
 materials.append({'id':p.stem,'path':str(p),'sha256':sha(p)})
for key,o in v['outputs'].items():
 assert sha(o['mesh'])==o['sha256'];assert o['orthogonal_fallback_vertex_count']==0;assert o['opposed_winding_triangles']==0;assert o['near_ambiguous_winding_triangles']==0 or key in ['donnager_pdc_base','donnager_pdc_barrel']
 if key in ['donnager_pdc_base','donnager_pdc_barrel']:
  part=key.rsplit('_',1)[1];expected=3 if part=='base' else 9;old_audit=read(ROOT/'audit/polish-b/output-validation.json')['outputs']['pdc_0_'+part];assert old_audit['near_ambiguous_winding_triangles']==o['near_ambiguous_winding_triangles']==expected;assert o['minimum_face_normal_cosine']>=-1e-5
  original=Gltf(ROOT/'assets/derived/polish-b'/('expanse_polish_pdc_0_'+part+'.gltf'));pr=original.g['meshes'][0]['primitives'][0];frame=read(OUT/'retained-source-frames.json')[key]['0'];ov=original.accessor(pr['attributes']['POSITION']);on=original.accessor(pr['attributes']['NORMAL']);ov[:,2]*=-1;on[:,2]*=-1;assert np.array_equal(ov,np.array(frame['positions']));assert np.array_equal(on,np.array(frame['normals']));assert np.array_equal(original.accessor(pr['attributes']['TEXCOORD_0']),np.array(frame['uv']));new_input=Gltf(OUT/('expanse10_'+key+'.gltf'));new_pr=new_input.g['meshes'][0]['primitives'][0];assert np.array_equal(np.sort(original.accessor(pr['indices']).reshape(-1,3),axis=1),np.sort(new_input.accessor(new_pr['indices']).reshape(-1,3),axis=1));inherited.append({'part':part,'unique_near_perpendicular_faces':expected,'instances_across16guns':expected*16,'old_min_cosine':old_audit['minimum_face_normal_cosine'],'new_min_cosine':o['minimum_face_normal_cosine'],'geometry_normals_uv_exactly_preserved_before_compile':True,'unordered_triangle_membership_exactly_preserved':True,'accepted_existing_tolerance':1e-5})
 for material in o['materials']:assert any(q['id']==material for q in materials),material
 meshes.append({'id':Path(o['mesh']).stem,'path':o['mesh'],'sha256':o['sha256'],'triangles':o['triangles'],'materials':o['materials']})
points=v['outputs']['donnager_hull']['meshpoints'];names={p['name'] for p in points};assert {'center','hangar.0','weapon.boarding.0','exhaust.0','exhaust.1','exhaust.2','exhaust.3'}<=names;assert len(meshes)==5
spec={'status':'PASS OFFLINE ONLY','runtime':'NOT RUN','game_directory':str(game),'hull_mesh':'expanse10_donnager_hull','rigs':m['rigs'],'spatial':m['ship_spatial'],'ship_spatial':m['ship_spatial'],'equipment':m['equipment'],'meshes':meshes,'materials':materials,'textures':textures,'unique_mesh_triangles':m['triangle_total'],'assembled_triangle_count':m['assembled_triangle_total'],'pdc_count':16,'railgun_count':2,'count_is_prototype_not_canonical':True,'rail_yaw_speed_override':15.0,'normalization':m['normalization'],'source_hashes':m['source_hashes'],'editable':str(OUT/'donnager10_editable.gltf'),'editable_compiler_z_reflected':False,'compiler_input_z_reflected':True,'offline_checks':[str(AUDIT/name) for name in ['output-validation.json','independent-checks.json','silhouette-comparison.json']],'meshpoints':points,'runtime_limits':['PDC tracking, nearby-hull obstruction and sector coverage NOT RUN','Rail ±2degree yaw sampled outside original bearing contact region only; exact internal and continuous clearance NOT VERIFIED','Corvette launch uses60units outside closed static source hatch; no door animation or open passage','Light front collars are custom prototype additions; aft circular aperture weapon meaning assigned for prototype','One-ship, formation and fleet performance NOT RUN'],'material_limitations':read(AUDIT/'material-resources.json'),'inherited_donor_near_perpendicular_faces':inherited};write(AUDIT/'integration-spec.json',spec);write(AUDIT/'resource-checks.json',{'status':'PASS OFFLINE ONLY','meshes':len(meshes),'materials':len(materials),'textures':len(textures),'all_mesh_material_texture_references_resolved':True,'zero_compiler_tangent_fallbacks':True,'required_boarding_and_four_exhaust_points':True,'inherited_donor_near_perpendicular_faces':inherited});print('PASS final resources:',len(meshes),'meshes',len(materials),'materials',len(textures),'DDS; spec',sha(AUDIT/'integration-spec.json'))
