"""Normalize and simplify supplied Sunflare while preserving actual UV/material assets."""
from pathlib import Path
import json,copy,ctypes as c,numpy as np,os
from common import Gltf
from polish_ui import write
ROOT=Path(__file__).resolve().parents[1];MASTER=ROOT/'assets/source/update12-sunflare';OUT=ROOT/'assets/derived/update12-c';AUD=ROOT/'audit/update12-c';BUILD=ROOT/'build/update12-c';MAIN=Path('/run/media/haker/NVME 2/expanse-mod');NAME='expanse12_sunflare_hull';a=Gltf(next(MASTER.glob('*.gltf')));p=a.g['meshes'][0]['primitives'][0];raw=a.accessor(p['attributes']['POSITION']);n=a.accessor(p['attributes']['NORMAL']);t=a.accessor(p['attributes']['TANGENT']);uv=a.accessor(p['attributes']['TEXCOORD_0']);idx=a.accessor(p['indices']).reshape(-1,3);R=np.array([[0,0,1],[1,0,0],[0,1,0]],float);assert np.linalg.det(R)==1;center=(raw.min(0)+raw.max(0))/2;length=12/46*105;scale=length/np.ptp(raw[:,1]);v=(raw-center)@R.T*scale;n=n@R.T;t[:,:3]=t[:,:3]@R.T
lib=c.CDLL(str(MAIN/'.tools/libmeshoptimizer.so'));u=c.POINTER(c.c_uint);f=c.POINTER(c.c_float);fn=lib.meshopt_simplifyWithAttributes;fn.argtypes=[u,u,c.c_size_t,f,c.c_size_t,c.c_size_t,f,c.c_size_t,f,c.c_size_t,c.POINTER(c.c_ubyte),c.c_size_t,c.c_float,c.c_uint,f];fn.restype=c.c_size_t
v=np.ascontiguousarray(v,dtype='float32');attrs=np.ascontiguousarray(np.column_stack([n,uv]),dtype='float32');ii=np.ascontiguousarray(idx.ravel(),dtype='uint32');weights=np.array([.1,.1,.1,.2,.2],dtype='float32');dst=np.zeros_like(ii);err=c.c_float();num=fn(dst.ctypes.data_as(u),ii.ctypes.data_as(u),len(ii),v.ctypes.data_as(f),len(v),12,attrs.ctypes.data_as(f),20,weights.ctypes.data_as(f),5,None,18000*3,.012,32,c.byref(err));idx=dst[:num].reshape(-1,3);tri=v[idx].astype(float);cross=np.cross(tri[:,1]-tri[:,0],tri[:,2]-tri[:,0]);area=np.linalg.norm(cross,axis=1);edge=np.max(np.linalg.norm(tri-np.roll(tri,1,axis=1),axis=2),axis=1);keep=(area>1e-7)&(area/np.maximum(edge**2,1e-20)>1e-6);removed=int((~keep).sum());idx=idx[keep];flip=np.sum(cross[keep]*n[idx].mean(1),axis=1)<0;idx[flip]=idx[flip][:,[0,2,1]];used,remap=np.unique(idx,return_inverse=True);v=v[used];n=n[used];n/=np.linalg.norm(n,axis=1)[:,None];t=t[used];t[:,:3]-=n*np.sum(t[:,:3]*n,axis=1)[:,None];assert np.linalg.norm(t[:,:3],axis=1).min()>1e-6;t[:,:3]/=np.linalg.norm(t[:,:3],axis=1)[:,None];uv=uv[used];idx=remap.reshape(-1,3)
# Simplification can join opposite source corner normals. Correct only near-perpendicular
# averaged-normal faces with isolated corners and their longest-edge geometric frame for their collapsed source UVs (retaining UVs/handedness).
q=v[idx].astype(float);face=np.cross(q[:,1]-q[:,0],q[:,2]-q[:,0]);mean=n[idx].mean(1);cos=np.sum(face*mean,axis=1)/np.maximum(np.linalg.norm(face,axis=1)*np.linalg.norm(mean,axis=1),1e-15);correct=np.where(abs(cos)<=1e-5)[0]
for fi in correct:
 ids=idx[fi].copy();vv=v[ids].copy();normal=face[fi]/np.linalg.norm(face[fi]);edges=vv-np.roll(vv,1,axis=0);tangent3=edges[np.argmax(np.linalg.norm(edges,axis=1))];tangent3-=normal*np.dot(tangent3,normal);assert np.linalg.norm(tangent3)>1e-8;tangent3/=np.linalg.norm(tangent3);tangent=np.column_stack([np.tile(tangent3,(3,1)),t[ids,3]]);idx[fi]=np.arange(len(v),len(v)+3);v=np.concatenate([v,vv]);n=np.concatenate([n,np.tile(normal,(3,1))]);t=np.concatenate([t,tangent]);uv=np.concatenate([uv,uv[ids]])
# Measured central engine-bell mouth in local source coordinates. Review ray below.
ring=raw[(abs(raw[:,1]+8.372779)<1e-4)&(np.linalg.norm(raw[:,[0,2]],axis=1)<2.2)];assert len(ring)>=48;engine=(ring.min(0)+ring.max(0))/2;engine[1]=ring[:,1].min();ep=(engine-center)@R.T*scale;ep[2]-=.1;exhaust={'position':ep.tolist(),'forward':[0,0,-1],'up':[0,1,0],'source_local_position':engine.tolist(),'source':'Central engine bell aft mouth; side fins are not engine nozzles','source_offset_beyond_surface':.1,'source_ring_bounds':[ring.min(0).tolist(),ring.max(0).tolist()],'source_ring_vertices':len(ring)}
points=[{'name':'center','translation':[0,0,0]},{'name':'above','translation':[0,float(v[:,1].max()+1),0]},{'name':'aura','translation':[0,float(v[:,1].min()-1),0]},{'name':'exhaust.0','translation':ep.tolist(),'rotation':[0,1,0,0]}]
def save(name,compiler):
 g={'asset':{'version':'2.0','generator':'Supplied Sunflare derivative; proper local-to-game rotation'},'scene':0,'scenes':[{'nodes':[0]}],'nodes':[{'name':name,'mesh':0,'children':[]}],'meshes':[{'primitives':[]}],'materials':[copy.deepcopy(a.g['materials'][0])],'buffers':[],'bufferViews':[],'accessors':[]};g['materials'][0]['name']='expanse12_sunflare_material';buf=bytearray()
 if not compiler:
  g['images']=[{'uri':os.path.relpath(MASTER/i['uri'],OUT)}for i in a.g['images']];g['textures']=copy.deepcopy(a.g['textures']);g['samplers']=copy.deepcopy(a.g['samplers']);g['extensionsUsed']=a.g['extensionsUsed']
 else:g['materials']=[{'name':'expanse12_sunflare_material','pbrMetallicRoughness':{'baseColorFactor':[1,1,1,1]}}]
 def acc(value,typ,ct=5126):
  value=np.asarray(value,dtype='<f4'if ct==5126 else'<u4');buf.extend(b'\0'*((-len(buf))%4));start=len(buf);buf.extend(value.tobytes());g['bufferViews'].append({'buffer':0,'byteOffset':start,'byteLength':value.nbytes});at={'bufferView':len(g['bufferViews'])-1,'componentType':ct,'count':len(value),'type':typ}
  if typ=='VEC3':at.update(min=value.min(0).tolist(),max=value.max(0).tolist())
  g['accessors'].append(at);return len(g['accessors'])-1
 vv=v.copy();nn=n.copy();tt=t.copy()
 if compiler:vv[:,2]*=-1;nn[:,2]*=-1;tt[:,2]*=-1;tt[:,3]*=-1
 g['meshes'][0]['primitives']=[{'mode':4,'material':0,'indices':acc(idx.ravel(),'SCALAR',5125),'attributes':{'POSITION':acc(vv,'VEC3'),'NORMAL':acc(nn,'VEC3'),'TANGENT':acc(tt,'VEC4'),'TEXCOORD_0':acc(uv,'VEC2')}}]
 for p in points:
  p=copy.deepcopy(p)
  if compiler:
   p['translation'][2]*=-1
   if'rotation'in p:p['rotation'][0]*=-1;p['rotation'][1]*=-1
  g['nodes'][0]['children'].append(len(g['nodes']));g['nodes'].append(p)
 g['buffers']=[{'uri':name+'.bin','byteLength':len(buf)}];(OUT/(name+'.bin')).write_bytes(buf);write(OUT/(name+'.gltf'),g)
save(NAME,True);save('expanse12_sunflare_editable',False);write(OUT/'retained-source-frames.json',{'hull':{'0':{'v':v.tolist(),'n':n.tolist(),'t':t.tolist(),'uv':uv.tolist()}}});lo=v.min(0);hi=v.max(0);bc=(lo+hi)/2;spatial={'box':{'center':bc.tolist(),'extents':((hi-lo)/2).tolist()},'radius':float(np.linalg.norm(v-bc,axis=1).max()),'bounds_min':lo.tolist(),'bounds_max':hi.tolist()};meta={'status':'COMPILER PENDING','game_directory':str(BUILD/'game'),'hull_mesh':NAME,'rigs':[],'ship_spatial':spatial,'equipment':{'exhaust':exhaust,'exhausts':[exhaust]},'exhaust_geometry':exhaust,'counts':{'hull':len(idx)},'assembled_triangle_total':len(idx),'meshpoints':{'hull':points},'editable_source':str(OUT/'expanse12_sunflare_editable.gltf'),'normalization':{'source_mesh_local_center':center.tolist(),'proper_rotation':R.tolist(),'determinant':float(np.linalg.det(R)),'uniform_scale':float(scale),'game_length':length,'provisional_meters':12,'reference':'Tachi46m/105gameunits, provisional12m within requested10-15m envelope; no source physicalunit assertion','scene_root_transform':'Discarded arbitrary presentation transform; single unskinned mesh local geometry preserves relative scale and proportions'},'runtime':'NOT RUN'};write(AUD/'integration-spec.json',meta);write(AUD/'optimization.json',{'source_triangles':60635,'target_triangles':18000,'output_triangles':len(idx),'slivers_removed':removed,'relative_error':err.value,'error_limit':.012,'attribute_weights':weights.tolist(),'source_UV_preserved':True,'authored_tangent_frames_preserved_except_repaired_faces':True,'near_perpendicular_normal_faces_repaired':len(correct),'collapsed_UV_faces_geometric_edge_frame':len(correct),'fallback_tangents':0});np.savez(OUT/'optimized.npz',v=v,n=n,t=t,uv=uv,i=idx);print('Sunflare',len(idx),'triangles error',err.value,flush=True)
