"""Compare suspicious exterior rays with the untouched original source geometry."""
from pathlib import Path
import numpy as np,json,hashlib
from scipy.sparse import coo_matrix
from scipy.sparse.csgraph import connected_components
ROOT=Path(__file__).resolve().parents[1];AUD=ROOT/'audit/update14-hulls';z=np.load('/run/media/haker/NVME 2/expanse-workers/weapon-behavior/assets/derived/update12-a/source-welded.npz');v=z['v'];i=z['i'];opt=json.loads((AUD/'raptor/optimization.json').read_text());e=np.concatenate([i[:,[0,1]],i[:,[1,2]],i[:,[2,0]]]);_,lab=connected_components(coo_matrix((np.ones(len(e)),(e[:,0],e[:,1])),shape=(len(v),len(v))),directed=False);i=i[~np.isin(lab[i[:,0]],opt['removed_static_gun_components'])];v=(v-opt['source_center'])@np.array(opt['source_to_game_rotation']).T*opt['uniform_scale'];tri=v[i];rows=json.loads((AUD/'raptor/exterior-detail.json').read_text());result=[]
for row in rows:
 axis=row['axis'];sign=row['side'];xy=[q for q in range(3)if q!=axis];lo=tri[:,:,xy].min(1);hi=tri[:,:,xy].max(1)
 for fail in row['backface_hits']:
  pt=np.array(fail['projected_xy']);sel=np.where((lo<=pt).all(1)&(hi>=pt).all(1))[0];q=tri[sel];a=q[:,0,xy];e=q[:,1,xy]-a;f=q[:,2,xy]-a;s=pt-a;det=e[:,0]*f[:,1]-e[:,1]*f[:,0];valid=abs(det)>1e-10;sel=sel[valid];q=q[valid];a=a[valid];e=e[valid];f=f[valid];s=s[valid];det=det[valid];u=(s[:,0]*f[:,1]-s[:,1]*f[:,0])/det;w=(e[:,0]*s[:,1]-e[:,1]*s[:,0])/det;ok=(u>=0)&(w>=0)&(u+w<=1);depth=q[:,0,axis]+u*(q[:,1,axis]-q[:,0,axis])+w*(q[:,2,axis]-q[:,0,axis]);ids=np.where(ok)[0];k=ids[np.argmax(sign*depth[ids])];normal=np.cross(q[k,1]-q[k,0],q[k,2]-q[k,0]);normal/=np.linalg.norm(normal);result.append(dict(axis=axis,side=sign,projected_xy=pt.tolist(),restored_depth=fail['position_axis'],source_depth=float(depth[k]),source_normal=normal.tolist(),source_first_surface_backface=bool(normal[axis]*sign<0),source_component=int(lab[i[sel[k],0]])))
original=Path('/home/haker/Downloads/xxx_-_raptor_whole.stl');report={'original_sha256':hashlib.sha256(original.read_bytes()).hexdigest(),'source_signed_volume_game_units':float(np.einsum('ij,ij->i',tri[:,0],np.cross(tri[:,1],tri[:,2])).sum()/6),'anomaly_ray_source_comparison':result,'interpretation':'The residual grazing and exact-centerline rays hit small inward faces after reduction; untouched source rays hit outward faces. This is a bounded sampled exposure finding, not a watertightness pass. Inspect the bow centerline and small side details in game.','runtime':'NOT RUN'};(AUD/'source-orientation.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report,indent=2))
